[project]
name = "mi-proyecto"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "customtkinter>=5.2.2",
    "pygithub>=2.8.1",
    "requests>=2.32.5",
]

[dependency-groups]
dev = [
    "pyinstaller>=6.17.0",
]
